# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: dist

jobs:
# Please do not rename this job
  build-project:
    name: build frontend-w-strapi
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - if: ${{ github.ref == 'refs/heads/beta' || github.event.client_payload.beta == true }}
        name: Build Node assets BETA
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
          STRAPI_URL: ${{ secrets.DEV_STRAPI_URL }}
          STRIPE_PK: ${{ secrets.STRIPE_PK_TEST }}
          DONATION_1: ${{ secrets.DEV_DONATION_1 }}
          DONATION_2: ${{ secrets.DEV_DONATION_2 }}
          DONATION_3: ${{ secrets.DEV_DONATION_3 }}
          DONATION_4: ${{ secrets.DEV_DONATION_4 }}
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
          yarn build
          yarn generate
      
      - if: ${{ github.ref == 'refs/heads/master' && github.event.client_payload.beta != true }}
        name: Build Node assets MASTER
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
          STRAPI_URL: ${{ secrets.PROD_STRAPI_URL }}
          STRIPE_PK: ${{ secrets.STRIPE_PK_LIVE }}
          DONATION_1: ${{ secrets.PROD_DONATION_1 }}
          DONATION_2: ${{ secrets.PROD_DONATION_2 }}
          DONATION_3: ${{ secrets.PROD_DONATION_3 }}
          DONATION_4: ${{ secrets.PROD_DONATION_4 }}
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
          yarn build
          yarn generate

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 77285c6f-760a-46d2-a7fa-8504971a469c
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/frontend-w-strapi/config.yaml
          action: upload
