# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: dist

jobs:
# Please do not rename this job
  build-project:
    name: build frontend-w-strapi
    runs-on: ubuntu-latest
    environment: ${{ github.ref }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
          STRAPI_URL: ${{ vars.STRAPI_URL }}
          STRIPE_PK: ${{ vars.STRIPE_PK }}
          DONATION_1: ${{ vars.DONATION_1 }}
          DONATION_2: ${{ vars.DONATION_2 }}
          DONATION_3: ${{ vars.DONATION_3 }}
          DONATION_4: ${{ vars.DONATION_4 }}
        run: |
          echo "env : ${{ env.ENVIRONMENT }}"
          npm install --global yarn
          yarn install --frozen-lockfile
          yarn build
          yarn generate

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 77285c6f-760a-46d2-a7fa-8504971a469c
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/frontend-w-strapi/config.yaml
          action: upload
